<a href="https://colab.research.google.com/github/Clemente-H/Base-de-Datos-Multimdia/blob/main/todo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 47.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.3/190.3 KB 20.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 72.8 MB/s eta 0:00:00


In [ ]:
corpus = ["Concertación repostulará a mesa directiva censurada en la Cámara Baja", 
"Velocista estadounidense Mickey Grimes fue suspendido por dos años", 
"Jaime Valdés volvió a responder en triunfo de Fiorentina por Copa Italia", 
"Servette de Valdivia y Beausejour reconoció su crisis económica", 
"Gobierno venezolano negó vínculos de Chavez con ultranacionalista peruano", 
"Gobierno se comprometió a canalizar a través de Unicef la ayuda para países asiáticos", 
"Cristián Bustos cree que el ciclismo será su punto débil en Pucón", 
"Para De la Peña, es demasiado honor la posibilidad de ser chileno", 
"Sebastián González y Atlante tuvieron un inicio para olvidar en torneo Interliga", 
"Rusia se inclinó ante Alemania en su debut en la Copa Hopman", 
"Patricio Galaz debutó en intenso empate de Atlante contra Guadalajara", 
"Boston College apabulló a UC del Maule en el Campinoni del Domani", 
"Walker llamó a los chilenos a colaborar en campaña solidaria por Asia", 
"Valdivia sigue imponiendo sus términos en el Campioni del Domani", 
"Deportes Valdivia y Boston College jugarán la final del Domani", 
"Deportes Valdivia consiguió su cuarta victoria consecutiva en el Domani", 
"UDI presentó una censura contra la mesa de la Cámara Baja", 
"Gabriel Ascencio fue confirmado como presidente de la Cámara Baja", 
"Cámara Baja aprobó censura contra la mesa directiva", 
"Alicante de España confirmó su interés en Juan Pablo Ubeda", 
"Lance Armstrong no tiene previsto participar en el Tour de Francia 2005", 
"Buffon volvió a ser el mejor portero para la federación de estadísticas", 
"Agassi se rindió ante el poderío de Federer: Hace todo bien", 
"Atlante calificó de reprobable la actitud de Sebastián González", 
"Jaguares venció a Toluca y dejó a América fuera de la Libertadores", 
"Eslovaquia apabulló a Argentina para quedarse con la Copa Hopman", 
"Eslovaquia avanzó a la final de la Copa Hopman para chocar con Argentina", 
"Milovan Mirosevic cree improbable partir al fútbol portugués", 
"Alvaro Fillol comentó las novedades del ATP de Viña del Mar 2005", 
"El ATP de Viña del Mar se adueña del tenis", 
"Felipe Parada será el primer chileno en ver acción en Viña del Mar", 
"Celta de Pablo Contreras consiguió un triunfo sobre Almería", 
"Ex modelo demandó a Javier Bardem por romperle la nariz", 
"Gabriel Ascencio sucederá a Lorenzini en la presidencia de la Cámara", 
"Rebeldes depusieron las armas y abandonaron comisaría en Andahuaylas", 
"Manuel Contreras ingresó al penal Cordillera para cumplir sentencia de 12 años", 
"Ricardo Rojas lideró zaga de América en valioso triunfo en torneo Interliga", 
"Argentino Juan Ignacio Chela se borró del ATP de Viña por lesión", 
"Marcelo Espina logró su primer triunfo como entrenador de Colo Colo", 
"Sebastián Pardo brilló en sólo 45 minutos como titular en Feyenoord", 
"Deportes Valdivia se coronó campeón invicto del Campioni del Domani", 
"Llanquihue fue la sorpresa en la cuarta jornada del Campioni del Domani", 
"Cristián Bustos espera al menos repetir su tercer lugar de 2004 en Pucón", 
"Médicos que colaboraron con víctimas de maremoto regresaron a Chile", 
"Armstrong lució nuevo equipo, mientras sigue analizando correr el Tour 2005", 
"Nacionalización de Horacio de la Peña superó primer trámite en el Congreso", 
"Velasco cree que Chiledeportes mantendrá la línea pese a su salida", 
"Udinese y Pizarro sufrieron para clasificarse en la Copa Italia", 
"González espera un jugador de la qualy para iniciar su ruta en Viña del Mar", 
"Zamorano aseguró que de aquí a julio se definirá el paso de Maldonado a Real Madrid", 
"Lleyton Hewitt hizo valer su condición de local en torneo de Adelaida", 
"Servette logró una prórroga para evitar su quiebra", 
"Pablo Galdames desea permanecer en Quilmes porque el fútbol chileno no está bien", 
"Mario Salgado le salvó un punto a Ternana por la Serie B de Italia", 
"Armstrong está decepcionado por investigación de la Justicia francesa", 
"Inter de Milán tomó ventaja en la ida de cuartos de final de la Copa Italia", 
"Pablo Contreras afirmó la zaga de Celta en valioso triunfo sobre Xerez", 
"Javier Bardem fue asaltado en playa brasileña", 
"Gabriel Ascencio fue ratificado como nuevo presidente de la Cámara Baja", 
"Beckham afirmó que volvería a Manchester si dejara Real Madrid", 
"Ronaldo viajó urgentemente a Brasil debido a problemas familiares", 
"Hitchcock fue el director que más merecía un Oscar, según sondeo", 
"Tribunal surcoreano ratificó condena de cárcel para vicepresidente del COI", 
"Cancillería confirmó muerte de ciudadana sueca de origen chileno en Tailandia", 
"Markus Merk destronó a Collina como el mejor árbitro del mundo", 
"La Ley encabezará campaña de Televisa para víctimas de tsunami", 
"Chile luchará por el bronce en el Seven de Punta del Este", 
"Thierry Henry encabezará campaña en contra del racismo en el fútbol", 
"Argentina arrancó con el pie derecho en la Copa Hopman", 
"Eslovaquia instaló el suspenso en el Grupo B de la Copa Hopman", 
"Pablo Galdames está para pelear la camiseta con cualquiera en Quilmes", 
"Van de Wyngard firmó su hazaña al ganar dos pruebas en un mismo fin de semana", 
"Lleyton Hewitt revalidó su título en Sidney tras derrotar a Ivo Minar", 
"Lleyton Hewitt se despidió del torneo de Adelaida", 
"Marcelo Espina se sintió incómodo al ser vinculado a la banca de Colo Colo", 
"Tigres clasificó directamente a Copa Libertadores tras batir a Toluca", 
"U. Católica avanzó en el Domani, pese a perder el clásico ante U. de Chile", 
"Cruzeiro desconoció interés de Real Madrid por Claudio Maldonado", 
"El bicampeón Estados Unidos inició con solidez la Copa Hopman 2005", 
"Pelé y Romario olvidaron las ofensas y fumaron la &#147;pipa de la paz&#148;", 
"Romario: Cuando está callado, Pelé es un poeta", 
"Mourinho fue elegido como el mejor técnico del mundo en 2004", 
"Chile comenzó 2005 como el penúltimo equipo sudamericano del ranking FIFA", 
"Detractores de Horacio de la Peña divulgaron contenido de polémica carta", 
"Justicia gala investigará entorno de Lance Armstrong por sospechas de dopaje", 
"Nicolás Córdova llega a Ascoli a buscar la posibilidad de jugar", 
"Iván Zamorano hizo su aporte para los damnificados por el maremoto", 
"Milovan Mirosevic festejó con Racing en el clásico ante Independiente", 
"Argentina eliminó a Rusia de la Copa Hopman", 
"Patricio Galaz tendrá la opción de debutar este miércoles en Atlante",
"Autoridades y rebeldes reanudaron el diálogo en Andahuaylas", 
"Toledo anunció mano dura para seguidores de Antauro Humala", 
"Ministro peruano del Interior renunció tras críticas por rebelión en Andahuaylas", 
"Derecha quiere impedir que diputados censurados ocupen cargos directivos", 
"Español derrotó a U. de Chile en el inicio del Campioni del Domani", 
"Ternana de Luis Jiménez tuvo que conformarse con una paridad como local", 
"Cristián Bustos mostró su vigencia y se impuso en triatlón de Concepción", 
"Francisco Vidal se reunió con empresarios que se sumaron a campaña por Asia", 
"Regresaron especialistas que colaboraron en identificación de cuerpos en Tailandia", 
"Técnico de Grecia fue el mejor seleccionador de 2004 para la IFFHS", 
"U. de Concepción fue el mejor equipo chileno en el ranking mundial 2004", 
"El colista de la Serie A eliminó a Juventus de la Copa Italia", 
"Prensa brasileña afirmó que Maldonado está cada vez más cerca de Real Madrid", 
"Claudio Maldonado tuvo un exitoso debut en el Campeonato Mineirao", 
"Derrota ante Italia concretó el fracaso de Safin y Myskina en la Copa Hopman", 
"Hermana de Richard Krajicek le permitió a Holanda ingresar a la Copa Hopman", 
"La localía no bastó a Stadio Italiano ante Boston College en el Domani", 
"Gran actuación de Ruiz fue insuficiente para Santos Laguna en empate ante Chivas", 
"Lleyton Hewitt cumplió en su debut en el torneo de su natal Adelaida", 
"Gastón Gaudio aseguró su participación en el ATP de Viña del Mar 2005", 
"América hipotecó su presencia en la Libertadores con empate ante Necaxa", 
"Pablo Galdames vio acción en empate de Quilmes ante Banfield", 
"Pablo Contreras no pudo reencontrarse con el triunfo junto a Celta", 
"Cifras de 2004 muestran el despegue de la música digital pagada", 
"Luis Jiménez comandó triunfo de Ternana en la Serie B", 
"Pelé le contestó a Romario: El bajito es muy nervioso", 
"Lesión obligó a Cristián Bustos a abandonar el Half Ironman de Pucón", 
"Cámara de Diputados aprobó nacionalización de Horacio de la Peña", 
"Gobierno dará suma urgencia a proyecto para nacionalizar a De la Peña", 
"Galaz fue nombrado oficialmente como máximo goleador del mundo en 2004"]

In [ ]:
import torch
from transformers import BertTokenizer, BertForQuestionAnswering

# Cargar el modelo pre-entrenado BERT
tokenizer = BertTokenizer.from_pretrained("dccuchile/bert-base-spanish-wwm-cased")
model = BertForQuestionAnswering.from_pretrained("dccuchile/bert-base-spanish-wwm-cased")

Some weights of the model checkpoint at dccuchile/bert-base-spanish-wwm-cased were not used when initializing BertForQuestionAnswering: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.bias', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertForQuestionAnswering from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForQuestionAnswering from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForQuestionAnswering were not initialized from the model checkpoint at dccuchile/bert-base-spanish

In [ ]:
p1 = "videojuegos"
p2 = "Pokedex"
p3 = "Steam"

In [ ]:
# Crear la pregunta utilizando las palabras de entrada "X, Y, Z"
question = "¿Cuál es la palabra que relaciona las palabras " + p1 +"," + p2 + "" + p3 + "?"

# Codificar la pregunta y el texto de referencia (en este caso, vacío)
encoded_question = tokenizer.encode(question, add_special_tokens=True)
encoded_text = tokenizer.encode("", add_special_tokens=True)

In [ ]:
# Ejecutar el modelo para generar una respuesta
inputs = torch.tensor([encoded_question, encoded_text])
start_scores, end_scores = model(inputs)

# Obtener la respuesta
answer_start = torch.argmax(start_scores)
answer_end = torch.argmax(end_scores)
answer = tokenizer.decode(encoded_question[answer_start:answer_end+1])

# Imprimir respuesta
print("Respuesta:", answer)

ValueError: ignored


# SBERT - Agglomerative Clustering

In [ ]:
!pip install sentence-transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 KB 3.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 24.6 MB/s eta 0:00:00
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125938 sha256=a51ec939f0c8bbc920f4db1f3a074f1e2957ca2820cc34c0620fa3d8fcc3fec6
  Stored in directory: /root/.cache/pip/wheels/5e/6f/8c/d88aec621f3f542d26fac0342bef5e693335d125f4e54aeffe
Successfully built sentence-transformers


In [ ]:
from sentence_transformers import SentenceTransformer
from sklearn.cluster import AgglomerativeClustering
import numpy as np

embedder = SentenceTransformer('symanto/sn-xlm-roberta-base-snli-mnli-anli-xnli')

In [ ]:
corpus_embeddings = embedder.encode(corpus)

# Normalize the embeddings to unit length
corpus_embeddings = corpus_embeddings /  np.linalg.norm(corpus_embeddings, axis=1, keepdims=True)

In [ ]:
# Perform kmean clustering
clustering_model = AgglomerativeClustering(n_clusters=None, distance_threshold=1.5) #, affinity='cosine', linkage='average', distance_threshold=0.4)
clustering_model.fit(corpus_embeddings)
cluster_assignment = clustering_model.labels_

clustered_sentences = {}
for sentence_id, cluster_id in enumerate(cluster_assignment):
    if cluster_id not in clustered_sentences:
        clustered_sentences[cluster_id] = []

    clustered_sentences[cluster_id].append(corpus[sentence_id])

In [ ]:
for i, cluster in clustered_sentences.items():
    print("Cluster ", i+1)
    print(cluster)
    print("")

Cluster  20
['Concertación repostulará a mesa directiva censurada en la Cámara Baja', 'UDI presentó una censura contra la mesa de la Cámara Baja', 'Cámara Baja aprobó censura contra la mesa directiva', 'Derecha quiere impedir que diputados censurados ocupen cargos directivos']

Cluster  12
['Velocista estadounidense Mickey Grimes fue suspendido por dos años', 'Manuel Contreras ingresó al penal Cordillera para cumplir sentencia de 12 años', 'Ternana de Luis Jiménez tuvo que conformarse con una paridad como local']

Cluster  17
['Jaime Valdés volvió a responder en triunfo de Fiorentina por Copa Italia', 'Udinese y Pizarro sufrieron para clasificarse en la Copa Italia', 'Mario Salgado le salvó un punto a Ternana por la Serie B de Italia', 'El colista de la Serie A eliminó a Juventus de la Copa Italia']

Cluster  4
['Servette de Valdivia y Beausejour reconoció su crisis económica', 'Atlante calificó de reprobable la actitud de Sebastián González', 'Llanquihue fue la sorpresa en la cuarta j

# WMDISTANCE

In [ ]:
import pandas as pd
import gensim
# Import and download stopwords from NLTK.
from nltk.corpus import stopwords
from nltk import download
download('stopwords')  # Download stopwords list.
stop_words = stopwords.words('spanish')
def preprocess(sentence):
    return [w for w in sentence.lower().split() if w not in stop_words]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
import gensim.downloader as api
from gensim.models import Word2Vec, KeyedVectors
model = KeyedVectors.load_word2vec_format('http://dcc.uchile.cl/~jperez/word-embeddings/fasttext-sbwc.vec.gz', binary=False)

In [ ]:
#http://cs.famaf.unc.edu.ar/~ccardellino/SBWCE/SBW-vectors-300-min5.bin.gz

FileNotFoundError: ignored

In [ ]:
def distancia_similitud(document1,document2,n_palabras):    
    # Identificar las palabras con mayor contribución en la distancia
    contributing_words = {}
    for word in set(document1 + document2):
        contributing_words[word] = abs(model.wmdistance([word],document1) - model.wmdistance([word],document2))
    
    # Ordenar las palabras por contribución a la distancia
    sorted_contributing_words = sorted(contributing_words.items(), key=lambda x: x[1], reverse=True)
    return sorted_contributing_words[:n_palabras],sorted_contributing_words[n_palabras:]

In [ ]:
a = preprocess('Concertación repostulará a mesa directiva censurada en la Cámara Baja')
b = preprocess('UDI presentó una censura contra la mesa de la Cámara Baja')

In [ ]:
print(distancia_similitud(a,b,3))

([('directiva', 1.0841840915171916), ('udi', 1.062898653872737), ('concertación', 0.7366811788450613)], [('presentó', 0.6668585986787097), ('censurada', 0.6369727521033193), ('mesa', 0.2069761846435565), ('baja', 0.13785261877121524), ('repostulará', nan), ('censura', 0.5015044735198027), ('cámara', 0.013863692792240201)])


In [ ]:
print(model.wmdistance(a,b))

2.468680412775081


# Comparando cos softCos y WMD

In [ ]:
sentence_1 = preprocess('Luego de cinco años Pokémon Go finalmente completó la Pokedex de tercera generación')
sentence_2 = preprocess('Naughty Dog no dará a conocer sus juegos hasta que estén cerca de su lanzamiento')
sentence_3 = preprocess('Steam supera por primera vez los 10 millones de usuarios simultáneos jugando')
sentence_4 = preprocess('Una buena y una mala para el bolsillo: baja la bencina de 93 y sube la de 97 a partir de este jueves')
sentence_5 = preprocess('Bencinas siguen al alza: a partir de este jueves subirán $2,1 y $10 por litro')
sentence_6 = preprocess('Ministro Marcel ve con optimismo la baja del dólar y califica su efecto en el precio de las bencinas como “favorable” para los consumidores')
sentence_7 = preprocess('Expectativas de IPC para marzo llegan hasta 1,4 e inflación anual superaría el 8%, su mayor nivel desde 2008')
#Se me prendió la luz de la bencina... ¿cuántos kilómetros me quedan? 
#2020
#Bencina
sentence_8 = preprocess('Es una escena más que común ver en la autopista un auto que se quedó en pana de bencina… la “pana del tonto”, como le llaman habitualmente. Es que con los altos precios de la bencina en nuestro país, no es de extrañar que muchos opten por circular con el combustible justo para ir y volver. Si eres de esos que andan siempre al límite, te contamos que lamentablemente no es la mejor idea. Seguro alguien ya te dijo que en el fondo del tanque se acumulan residuos del combustible, ya sea bencina o diésel. Bueno, esos residuos son reales, y cuando llega el momento de usar la reserva y bombearla hacia los inyectores, esos residuos hacen que el sistema trabaje en exceso. No solo estarás acortando la vida útil del filtro, en casos muy inoportunos, las impurezas pueden llegar a los inyectores, y ahí comienza a sufrir la billetera. Lo más recomendable, según los expertos, es mantener el estanque por la mitad, lo que nos asegura un funcionamiento óptimo (si quieres llenarlo, mucho mejor), y de paso se evitan posibles bolsas de aire ocasionadas por un menor bombeo. Sea como sea, poner un poco más de combustible en el estanque siempre te va a ahorrar problemas a futuro.')
#Hasbún y dirigentes de taxis colectivos se manifiestan contra nueva alza de bencinas
#2014
#alza, Bencina
sentence_9 = preprocess('El diputado y vicepresidente de la UDI, Gustavo Hasbún, se refiere a la nueva alza de las bencinas y emplaza al Gobierno a buscar una solución que permita rebajar o disminuir el impuesto especí­fico, "y no soluciones de parche".')

sentence_10 = preprocess("Szeth hijo hijo Vallano, sin verdad de Shinovar, vestía de blanco el día que iba a matar a un rey")
sentences = [sentence_1,sentence_2,sentence_3,sentence_4,sentence_5,sentence_6,sentence_7,sentence_8,sentence_9,sentence_10]

In [ ]:
#WMD
import numpy as np
a = np.zeros((10,10))
for i in range(0,10):
    for j in range(0,10):
        distance = model.wmdistance(sentences[i], sentences[j])
        a[i,j] = format_float = "{:.4f}".format(distance)
        #print('distance ',i,',',j,'=', distance )

In [ ]:
print(a)

[[0.     4.6511 4.2588 4.6781 4.9172 4.9757 4.818  4.6057 4.8575 4.6987]
 [4.6511 0.     4.7112 4.9157 5.1174 5.1731 5.098  4.8541 4.9926 4.9728]
 [4.2588 4.7112 0.     4.5853 4.8457 4.7046 4.5425 4.5436 4.7449 4.8722]
 [4.6781 4.9157 4.5853 0.     3.4578 4.2865 4.6055 4.2973 4.5769 4.6359]
 [4.9172 5.1174 4.8457 3.4578 0.     4.8658 4.7419 4.72   4.8554 5.0022]
 [4.9757 5.1731 4.7046 4.2865 4.8658 0.     4.6414 4.7433 4.6352 4.9762]
 [4.818  5.098  4.5425 4.6055 4.7419 4.6414 0.     4.6455 4.7076 4.8975]
 [4.6057 4.8541 4.5436 4.2973 4.72   4.7433 4.6455 0.     4.5055 4.6035]
 [4.8575 4.9926 4.7449 4.5769 4.8554 4.6352 4.7076 4.5055 0.     4.7916]
 [4.6987 4.9728 4.8722 4.6359 5.0022 4.9762 4.8975 4.6035 4.7916 0.    ]]


In [ ]:
#COS SIM
s_1 = 'Luego de cinco años Pokémon Go finalmente completó la Pokedex de tercera generación'
s_2 = 'Naughty Dog no dará a conocer sus juegos hasta que estén cerca de su lanzamiento'
s_3 = 'Steam supera por primera vez los 10 millones de usuarios simultáneos jugando'
s_4 = 'Una buena y una mala para el bolsillo: baja la bencina de 93 y sube la de 97 a partir de este jueves'
s_5 = 'Bencinas siguen al alza: a partir de este jueves subirán $2,1 y $10 por litro'
s_6 = 'Ministro Marcel ve con optimismo la baja del dólar y califica su efecto en el precio de las bencinas como “favorable” para los consumidores'
s_7 = 'Expectativas de IPC para marzo llegan hasta 1,4 e inflación anual superaría el 8%, su mayor nivel desde 2008'
s_8 = 'Es una escena más que común ver en la autopista un auto que se quedó en pana de bencina… la “pana del tonto”, como le llaman habitualmente. Es que con los altos precios de la bencina en nuestro país, no es de extrañar que muchos opten por circular con el combustible justo para ir y volver. Si eres de esos que andan siempre al límite, te contamos que lamentablemente no es la mejor idea. Seguro alguien ya te dijo que en el fondo del tanque se acumulan residuos del combustible, ya sea bencina o diésel. Bueno, esos residuos son reales, y cuando llega el momento de usar la reserva y bombearla hacia los inyectores, esos residuos hacen que el sistema trabaje en exceso. No solo estarás acortando la vida útil del filtro, en casos muy inoportunos, las impurezas pueden llegar a los inyectores, y ahí comienza a sufrir la billetera. Lo más recomendable, según los expertos, es mantener el estanque por la mitad, lo que nos asegura un funcionamiento óptimo (si quieres llenarlo, mucho mejor), y de paso se evitan posibles bolsas de aire ocasionadas por un menor bombeo. Sea como sea, poner un poco más de combustible en el estanque siempre te va a ahorrar problemas a futuro.'
s_9 = 'El diputado y vicepresidente de la UDI, Gustavo Hasbún, se refiere a la nueva alza de las bencinas y emplaza al Gobierno a buscar una solución que permita rebajar o disminuir el impuesto especí­fico, "y no soluciones de parche".'
s_10 = "Szeth hijo hijo Vallano, sin verdad de Shinovar, vestía de blanco el día que iba a matar a un rey"
s_all =[s_1,s_2,s_3,s_4,s_5,s_6,s_7,s_8,s_9,s_10]

# Scikit Learn
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Create the Document Term Matrix
count_vectorizer = CountVectorizer(stop_words='spanish')
count_vectorizer = CountVectorizer()
sparse_matrix = count_vectorizer.fit_transform(s_all)

# OPTIONAL: Convert Sparse Matrix to Pandas Dataframe if you want to see the word frequencies.
doc_term_matrix = sparse_matrix.todense()
df = pd.DataFrame(doc_term_matrix, 
                  columns=count_vectorizer.get_feature_names_out(), 
                  index=['1', '2', '3','4','5','6','7','8','9','10'])
#print(df)
from sklearn.metrics.pairwise import cosine_similarity
print(cosine_similarity(df, df))




[[1.         0.13801311 0.1490712  0.37712362 0.1490712  0.16151457
  0.12909944 0.2549012  0.31139958 0.22019275]
 [0.13801311 1.         0.07715167 0.14638501 0.07715167 0.11145564
  0.20044593 0.21987317 0.20145574 0.17094086]
 [0.1490712  0.07715167 1.         0.15811388 0.25       0.12038585
  0.07216878 0.17811762 0.13055824 0.12309149]
 [0.37712362 0.14638501 0.15811388 1.         0.31622777 0.3045548
  0.22821773 0.39052512 0.4679096  0.27247463]
 [0.1490712  0.07715167 0.25       0.31622777 1.         0.12038585
  0.07216878 0.1424941  0.26111648 0.12309149]
 [0.16151457 0.11145564 0.12038585 0.3045548  0.12038585 1.
  0.20851441 0.36881689 0.28291258 0.13336627]
 [0.12909944 0.20044593 0.07216878 0.22821773 0.07216878 0.20851441
  1.         0.15425439 0.18844459 0.15990054]
 [0.2549012  0.21987317 0.17811762 0.39052512 0.1424941  0.36881689
  0.15425439 1.         0.43408818 0.3069467 ]
 [0.31139958 0.20145574 0.13055824 0.4679096  0.26111648 0.28291258
  0.18844459 0.434088

In [ ]:
#SOFCOS
from gensim import corpora
from gensim.utils import simple_preprocess
import gensim.downloader as api
from gensim.models import TfidfModel
#from gensim.matutils import softcossim 
dictionary = corpora.Dictionary(sentences)

#similarity_matrix = fasttext_model300.similarity_matrix(dictionary, tfidf=None, threshold=0.0, exponent=2.0, nonzero_limit=100)
#pd.DataFrame(X_train_counts.toarray(),columns=count_vect.get_feature_names(),index=['sentence_1','sentence_2','sentence_3','sentence_4','sentence_5','sentence_6','sentence_7','sentence_8','sentence_9','sentence_10'])
sentences2 = []
for i in range(10):
    sentences2.append(dictionary.doc2bow(sentences[i]))
    #aux=sentences[i]
    #sentences2[i]= dictionary.doc2bow(aux)
    #aux = " ".join(str(x) for x in sentences[i])
    #print(sentences[i])
    #print(simple_preprocess(aux))
tfidf = TfidfModel(sentences2)

In [ ]:
from gensim.similarities import SparseTermSimilarityMatrix, WordEmbeddingSimilarityIndex
termsim_index = WordEmbeddingSimilarityIndex(model)
termsim_matrix = SparseTermSimilarityMatrix(termsim_index, dictionary, tfidf)

ImportError: ignored

In [ ]:
b = np.zeros((10,10))
for i in range(0,10):
    for j in range(0,10):
        distance = termsim_matrix.inner_product(sentences2[i], sentences2[j], normalized=(True, True))
        b[i,j] = format_float = "{:.4f}".format(distance)
        print('distance ',i,',',j,'=', distance )